
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314zps
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: logos\demo\demo.log
#  level:
server:
  servlet:
    context-path: /zxhw #表示上下文环境